# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalyshevAsk', '0003_question_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
