# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-14 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalyshevAsk', '0004_auto_20171114_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(),
        ),
    ]
