# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 15:05
from __future__ import unicode_literals

import MalyshevAsk.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MalyshevAsk', '0006_auto_20171205_1516'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', MalyshevAsk.models.UserM()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='upload',
            new_name='avatar',
        ),
    ]
