# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-10 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MalyshevAsk', '0008_auto_20171205_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nick',
            field=models.CharField(default='noNick', max_length=20),
            preserve_default=False,
        ),
    ]
